(define-page comment-posted "Comment posted"
    (stylesheet-link "/paleolithic.css")
      `((div (@ (class "header"))
             (h1 "Post a new comment")
             (h2 "Comment posted successfully..."))
        (br)
        (div (@ (class "site_content"))
             (div (@ (class "post"))
                  (h1 "Result")
                  ,(cdar (handle-post))))))
