(define (comment-posted #!rest args)
  (define-page "Comment posted"
    (stylesheet-link "/paleolithic.css")
    (lambda ()
      `((div (@ (class "header"))
             (h1 "Post a new comment")
             (h2 "Comment posted successfully..."))
        (br)
        (div (@ (class "site_content"))
             (div (@ (class "post"))
                  (h1 "Result")
                  ,(cdar (handle-post))))))))
