(define (make-form-post)
  `((div (@ (class "content"))
         (form (@ (method post) (action "comment-posted"))
               ,(textfield 'title "title" 'textbox)
               (br)
               (br)
               (textarea (@ (cols 80) (rows 10) (name post_message)))
               (br)
               (br)
               (input (@ (type submit) (value "Submit")))
               (input (@ (type reset) (value "Clear")))))))

(define-page post "Post a new comment"
    (stylesheet-link "/paleolithic.css")
      `((div (@ (class "header"))
             (h1 "New blog post")
             (h2 "Lambda"))
        (br)
        (div (@ (class "site_content"))
             (div (@ (class "post"))
                  ,(make-form-post)))))
